#!/bin/sh
URL="https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US"
INSTALLPATH="/usr/local/src/"
FILENAME="firefoxdev-latest.tar.bz2"
cd $INSTALLPATH
# -c resume uncomplete download, -O rename file
wget -cO $FILENAME $URL
tar xvf $FILENAME
